# Configuración de conexión a la base de datos

# Esta sección contiene los parámetros necesarios para establecer una conexión 
#segura y exitosa con la base de datos.

# Dirección del host donde se encuentra alojada la base de datos.
host: 'Tu Host'

# El nombre de usuario utilizado para autenticarse y acceder a la base de datos.
user: 'Tu usuario'

# La contraseña asociada al usuario de la base de datos. Se recomienda encarecidamente 
# mantener esta información segura y confidencial.
password: 'Tu contraseña'

# El nombre de la base de datos a la que se desea conectar. Este nombre debe coincidir exactamente con el nombre 
# de la base de datos que se desea utilizar.
name: 'Nombre de la base de datos'
